spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: customer-service
          uri: lb:http://CUSTOMER-SERVICE
          predicates:
            - Path=/api/v1/customers/**  # Ensure double slashes are used
        - id: order-service
          uri: lb:http://ORDER-SERVICE
          predicates:
            - Path=/api/v1/orders/**  # Ensure double slashes are used
        - id: order-lines-service
          uri: lb:http://ORDER-SERVICE
          predicates:
            - Path=/api/v1/order-lines/**  # Ensure double slashes are used
        - id: product-service
          uri: lb:http://PRODUCT-SERVICE
          predicates:
            - Path=/api/v1/products/**  # Ensure double slashes are used
        - id: payment-service
          uri: lb:http://PAYMENT-SERVICE
          predicates:
            - Path=/api/v1/payments/**  # Ensure double slashes are used
        - id: notification-service
          uri: lb:http://NOTIFICATION-SERVICE
          predicates:
            - Path=/api/v1/notifications/**  # Ensure double slashes are used
server:
  port: 8222
